name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Package the app as a zip
      run: |
        mkdir -p release
        zip -r release/app.zip .  # Zip the entire application directory

    - name: Upload the zip as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-zip
        path: release/app.zip
